doki-theme/doki-theme-jetbrains

- build.gradle
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- src/main/kotlin/io/acari/doki/TheDokiTheme.kt
- src/main/kotlin/io/acari/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/acari/doki/stickers/StickerComponent.kt
- src/main/kotlin/io/acari/doki/themes/impl/ThemeManagerImpl.kt
- src/main/kotlin/io/acari/doki/util/ToolBox.kt
- src/main/resources/META-INF/plugin.xml
Removed fancy Java 11 optional API usage.
#202 
Works in this environment
```
Android Studio 4.0 Canary 8
Build #AI-193.5233.102.40.6107147, built on January 2, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 amd64
Linux 4.15.0-74-generic
Memory: 1979M
Cores: 12
Registry: bigger.font.in.project.view=true, ide.new.welcome.screen.force=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.jetbrains.ChooseRuntime, io.acari.DDLCTheme
```
> Java 8 support

- build.gradle
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- gradle.properties
- src/main/kotlin/io/acari/doki/notification/UpdateNotification.kt
- src/main/resources/META-INF/plugin.xml
- themes/definitions/literature/monika/dark/Monika_Dark.xml
- themes/definitions/literature/natsuki/dark/Natsuki_Dark.xml
- themes/definitions/literature/sayori/dark/Sayori_Dark.xml
- themes/definitions/literature/yuri/dark/Yuri_Dark.xml
- themes/definitions/mistress/eleniel/Eleniel.xml
- themes/definitions/mistress/sanya/Sanya.xml
- themes/definitions/mistress/syrena/Syrena.xml
- themes/definitions/mistress/wyla/Wyla.xml
- themes/templates/dark.scheme.template.xml
- themes/templates/light.scheme.template.xml
- themes/templates/light.v2.scheme.template.xml
For Some reason, PyCharm ignores the smart way to re-use colors using the base attributes.
#198 
```
PyCharm 2020.1 EAP (Professional Edition)
Build #PY-201.3803.74, built on January 24, 2020
PyCharm EAP User
Expiration date: February 23, 2020
Runtime version: 11.0.5+9-b674.2 amd64
Linux 4.15.0-74-generic
Memory: 1979M
Cores: 12
Registry: 
Non-Bundled Plugins: com.markskelton.one-dark-theme, io.acari.DDLCTheme
```
> PyCharm colors

- build.gradle
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- gradle.properties
- src/main/kotlin/io/acari/doki/config/ThemeConfig.kt
- src/main/kotlin/io/acari/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/acari/doki/settings/ThemeSettings.kt
- src/main/kotlin/io/acari/doki/settings/actors/ShowReadmeActor.kt
- todo
Building the plugin with the 2020 SDK, that way the Kotlin DSL creates the right UI stuff.
Also added `Don't Show Readme on startup settings option`.
Fixes the issue with the 2020 builds not having a settings menu.
As for the don't show readme, you can admire your theme's background art when you start a new project.
Works on this
```
Linux 4.15.0-91-generic
Memory: 512M
Cores: 12
Registry: ide.open.readme.md.on.startup=false
```
> 2020 Settings Menu Fix

- build.gradle
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/ide/DokiThemeColorAnnotator.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/settings/ThemeSettings.kt
- src/main/kotlin/io/unthrottled/doki/ui/status/ThemeStatusBarProvider.kt
- src/main/kotlin/io/unthrottled/doki/ui/status/ThemeStatusBarWidget.kt
- src/main/resources/META-INF/plugin.xml
- Migrated away from deprecated platform APIs.
- Made version upgrades more maintainable.
I want to make the theme more maintainable and not using deprecated platform APIs :smile: 
It works on 
```
Linux 4.15.0-99-generic
Memory: 512M
Cores: 4
```
> Address Deprecations

- build.gradle
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/config/ThemeConfig.kt
- src/main/kotlin/io/unthrottled/doki/settings/ThemeSettings.kt
- themes/definitions/konoSuba/darkness/dark/Darkness_Dark.xml
- themes/definitions/konoSuba/darkness/dark/darkness.dark.jetbrains.definition.json
- themes/definitions/luckyStar/konata/light/Konata_Light.xml
- themes/templates/dark.scheme.template.xml
- Small adjustments to Darkness's Dark theme and Konata's Light theme.
- Fixed issue where non-Doki themes would be replaced by Rem after restarting.
I would like a consistent experience across all themes :)
Works on this:
```
Linux 4.15.0-101-generic
Memory: 512M
Cores: 12
```
> Small Adjustments

- LICENSE
- build.gradle
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- themes/definitions/killLaKill/satsuki/satsuki.jetbrains.definition.json
- themes/templates/light.scheme.template.xml
Updated all the light theme's ignored file status to be the disabled color.
Light Konata's file system tree looks garbage without it.
Lol, works on my machine
| before | after |
| --- | --- |
| ![Screenshot from 2020-06-16 05-22-38](https://user-images.githubusercontent.com/15972415/84763516-f2fce480-af91-11ea-9716-c059b6595583.png) | ![Screenshot from 2020-06-16 05-21-27](https://user-images.githubusercontent.com/15972415/84763539-fabc8900-af91-11ea-95fc-2273a4d040c4.png) |
> Better light theme file status colors.

- build.gradle
- changelog/CHANGELOG.md
- src/main/kotlin/io/unthrottled/doki/ui/status/ThemeStatusBarProvider.kt
- src/main/kotlin/io/unthrottled/doki/ui/status/ThemeStatusBarWidget.kt
- Managing the Status bar component through the factory and not through the widget itself.
Fixes #243 
Works on:
```
IntelliJ IDEA 2020.2 EAP (Community Edition)
Build #IC-202.5792.28, built on June 17, 2020
Runtime version: 11.0.7+10-b944.12 amd64
Linux 4.15.0-106-generic
Memory: 512M
Cores: 12
```
> Status Bar Component Bug Fix

- .github/ISSUE_TEMPLATE/bug_report.md
- build.gradle
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/stickers/impl/StickerServiceImpl.kt
- src/main/kotlin/io/unthrottled/doki/util/ToolBox.kt
Some instances of Android Studio _still_ run on JRE 8.... Which is annoying when you try to use JRE 11 API's. 
Fixes #245 
Works on this:
```
Linux 4.15.0-106-generic
Memory: 512M
Cores: 12
```
> Android Studio Support

- build.gradle
- changelog/CHANGELOG.md
- src/main/resources/theme-schema/master.theme.schema.json
Not requiring `accentContrastColor` to be part of the master scheme color definition.
I added `accentContrastColor` to the base color template, so I don't need to define it in each theme. If it is not there it gives me an annoying warning.
Works on this:
```IntelliJ IDEA 2020.1 (Ultimate Edition)
Linux 4.15.0-109-generic
Memory: 512M
Cores: 12
```
Make it not do this:
> Not requiring accent contrast color

- build.gradle
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/themes/ThemeManager.kt
- src/main/kotlin/io/unthrottled/doki/themes/impl/ThemeManagerImpl.kt
- Rias Gremory's diff/merge colors are now the same as the other themes.
- Blue for changes to existing code
- Green for additions
- Showing update notification when project is loaded to avoid jumpy animation. 
Fixes #257 
Works on:
```
Linux 4.15.0-109-generic
Memory: 512M
Cores: 12
```
> Rias Diff/Merge

- README.md
- build.gradle
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- src/main/kotlin/io/unthrottled/doki/ui/TitlePaneUI.kt
- Changed the MacOS Title pane font color to be the `infoForeground` color when active.
The Windows 10 IDE uses the `infoForeground` color, so I wanted it to be consistent.
I haven't yet 😅 
> Titled Header update

- build.gradle
- changelog/CHANGELOG.md
- src/main/kotlin/io/unthrottled/doki/actions/MotivatorPromotion.kt
- src/main/kotlin/io/unthrottled/doki/assets/AssetManager.kt
- src/main/kotlin/io/unthrottled/doki/promotions/MotivatorPluginPromotionRunner.kt
- src/main/kotlin/io/unthrottled/doki/promotions/MotivatorPromotionDialog.kt
- src/main/resources/META-INF/plugin.xml
Plugin now downloads the motivator promotion assets on a separate thread, so that it can be used by the AWT event processing thread (UI Thread).
Not everybody has fast internet connection, so if the download takes longer than expected, the UI will freeze. This is not that big of a deal, because this runs when the user is away. However, I don't want any reported exceptions.
I added a `Thread.sleep(5000)` in the asset manager to proof of concept slow internet.
> Non blocking asset fetch

- build.gradle
- buildSrc/src/main/kotlin/BuildThemes.kt
- buildSrc/src/main/kotlin/Models.kt
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- src/main/kotlin/io/unthrottled/doki/stickers/impl/StickerServiceImpl.kt
- src/main/kotlin/io/unthrottled/doki/themes/DokiTheme.kt
- themes/definitions/danganronpa/ibuki/dark/ibuki.dark.jetbrains.definition.json
- themes/definitions/danganronpa/ibuki/light/ibuki.light.jetbrains.definition.json
- themes/definitions/killLaKill/ryuko/ryuko.jetbrains.definition.json
- themes/definitions/literature/natsuki/dark/natsuki.dark.jetbrains.definition.json
- themes/definitions/literature/natsuki/light/natsuki.light.jetbrains.definition.json
- themes/definitions/reZero/beatrice/beatrice.jetbrains.definition.json
- themes/definitions/reZero/emilia/dark/emilia.dark.jetbrains.definition.json
- themes/definitions/reZero/emilia/light/emilia.light.jetbrains.definition.json
- themes/definitions/reZero/ram/ram.jetbrains.definition.json
- themes/definitions/reZero/rem/rem.jetbrains.definition.json
Changed background anchoring for various themes.
Closes #267 
Some themes will have some parts of the waifu cut off. I don't really want to change their location, as it may affect other projects. Maybe later, but not now.
I ran through all themes on landscape.
**All affected themes**
> Able to adjust background image anchors

- build.gradle
- changelog/CHANGELOG.md
- src/main/kotlin/io/unthrottled/doki/assets/LocalAssetService.kt
- src/main/resources/META-INF/plugin.xml
Changed the local asset ledger to be a concurrent map.
Fixes [this issue](https://sentry.io/share/issue/400ca428d80e4837b204a4bc2e49723f/)
The `LocalAssetService` is a singleton and now that asset downloading can happen in many threads, there are edge cases where on thread is writing to the asset check map while the other is trying to serialize it into json. So I chose to change the map to a `ConcurrentMap` so that the asset check can be written to and updated at the same time.
See this [issue for more details](https://github.com/google/gson/issues/1159#issuecomment-330535301)
I can't reproduce it, but the plugin still works.
> Fixed multi-threaded local asset race condition.

- build.gradle
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/config/ThemeConfig.kt
- src/main/kotlin/io/unthrottled/doki/integrations/RestClient.kt
- src/main/kotlin/io/unthrottled/doki/settings/actors/StickerActor.kt
- src/main/kotlin/io/unthrottled/doki/stickers/StickerComponent.kt
- src/test/kotlin/io/unthrottled/doki/config/ThemeConfigTest.kt
Changed how the readable enum constants are picked from state.
When the user changes the value to an unrecognized value, the value will switch to default.
The users can modify the `doki_doki_theme.xml` which can cause these exceptions to happen (and break the entire plugin):
- [Incident One](https://sentry.io/share/issue/ebd9b6aeebbf4eb59f3421254a867c31)
- [Incident Two](https://sentry.io/share/issue/41dc6a5215254f7dac9809635016accc/)
I wrote tests and I also directly modified the xml, to make sure it worked.
> Theme Settings Fix

- build.gradle.kts
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/settings/ThemeSettings.kt
- src/main/kotlin/io/unthrottled/doki/ui/TitlePaneUI.kt
Only installing the custom framless MacOS title bar on jetbrains products.
The platform does not fully support it, plus there are some [reported bugs](https://sentry.io/share/issue/0765b090225d48acb26d806520d071fc/)
The title pane does not appear in Android Studio and it does Appear in Intellij Community 2020.3 EAP
> Remove Custom Android Studio Title Bar

- buildSrc/src/main/kotlin/BuildThemes.kt
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/hax/HackComponent.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/resources/icons/ide/rating.svg
- themes/templates/dark.scheme.template.xml
- themes/templates/light.scheme.template.xml
- Enhanced Rin's error and unused coloring usability.
- Lightend up Ishtar's dark blue color (for usability)
- Changed the XML attributes to be more consistent with the HTML attributes.
- Temporarily fixed [this 2020.3 icon issue](https://youtrack.jetbrains.com/issue/IDEA-254333)
The icon replacement bug was annoying.
Rin's unused and error type colors where hard to differentiate between the keyword and class colors, respectivily. 
Consistency is cool.
Works on 
```
IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
Build #IU-203.5419.21, built on October 28, 2020
Expiration date: November 27, 2020
Runtime version: 11.0.8+10-b1145.3 amd64
Linux 5.4.0-52-generic
Memory: 512M
Cores: …
```
> Better 2020.3 Support & Usability Enhancements

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/hax/SvgLoaderHacker.kt
- src/main/kotlin/io/unthrottled/doki/icon/ColorPatcher.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
Safely attempt to call other SVG patchers after my patcher runs.
Looks like I forgot to take into account other plugins that remove the SVG patcher from the look and feel on older builds. (This should not be an issue with the 2020.3)
Should address #290 
I couldn't reproduce it with:
```
IntelliJ IDEA 2020.2.3 (Edu)
Build #IE-202.7660.52, built on October 27, 2020
Runtime version: 11.0.8+10-b944.34 amd64
Windows 10 10.0
Memory: 1979M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.mallowigi, io.acari.DDLCTheme, zd.zero.waifu-motivator-plugin, com.chrisrm.idea.MaterialThemeUI
```
> 2020.2.3 Cross plugin compatibility

- buildSrc/src/main/kotlin/BuildThemes.kt
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/hax/HackComponent.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- themes/templates/base.laf.template.json
- Removing Icon Hack
- Fixed version control log hover color
- Fixed classes table hover color
Fixes #292
Works on 
```
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on November 30, 2020
Runtime version: 11.0.9+11-b1145.21 amd64
Linux 5.4.0-54-generic
Memory: 512M
Cores: 12
```
> Better 2020.3 Support

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/assets/LocalAssetService.kt
- src/main/resources/META-INF/plugin.xml
- Added `doki.theme.update.assets` registry action, when disabled the plugin will not update local assets.
- You can toggle this feature via `help` > `Find Action...` > `doki.theme.update.assets` 
Initial support for #324 
New stickers will be downloaded, but will not be updated when registry item is unchecked.
You can do this now!
> Added ability to prevent asset updates.

- changelog/CHANGELOG.md
- gradle.properties
- themes/definitions/danganronpa/ibuki/light/ibuki.light.jetbrains.definition.json
- themes/definitions/literature/sayori/light/sayori.light.jetbrains.definition.json
- themes/templates/dark.scheme.template.xml
- themes/templates/light.scheme.template.xml
- Better default inline parameter hint color
- Lighter Ibuki light wallpaper setting
- Updated light Sayori's completion match color
- Fixed more of the usability issues [found in this issue](https://github.com/doki-theme/doki-theme-jetbrains/issues/340).
> Consistency Updates

- README.md
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/java/io/unthrottled/doki/settings/ThemeSettingsUI.form
- src/main/java/io/unthrottled/doki/settings/ThemeSettingsUI.java
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/config/ThemeConfig.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/service/CustomFontSizeService.kt
- src/main/kotlin/io/unthrottled/doki/settings/ThemeSettings.kt
- src/main/kotlin/io/unthrottled/doki/settings/actors/CustomFontSizeActor.kt
- src/main/resources/messages/MessageBundle.properties
Added **Global Editor Font Size** will override any/all font size settings for your code editor font size.
This only applies to any Doki Themes. You must enable the `Override Editor Font Size` for this feature to take effect.
Closes #356 
> Global editor font size setting

- changelog/CHANGELOG.md
- gradle.properties
- src/main/java/io/unthrottled/doki/settings/ThemeSettingsUI.java
- src/main/kotlin/io/unthrottled/doki/stickers/EditorBackgroundWallpaperService.kt
- src/main/resources/META-INF/plugin.xml
- Fixed compatibility issue that prevented the settings menu from displaying in the ^2020.3.2 builds 
Fixes #366 
Tested on
```
PhpStorm 2020.3.3
Build #PS-203.7717.64, built on March 16, 2021
You have a perpetual fallback license for this version.
Subscription is active until February 20, 2022.
Runtime version: 11.0.10+8-b1145.96 amd64
Linux 5.4.0-67-generic
Memory: 725M
Cores: 4
Registry: run.processes.with.pty=TRUE
```
> 2020.3 compatibility issue fix

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/assets/AssetManager.kt
- src/main/kotlin/io/unthrottled/doki/integrations/RestClient.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/stickers/EditorBackgroundWallpaperService.kt
- src/main/resources/META-INF/plugin.xml
- Fixed issue with plugin content not able to be downloaded when the IDE is configured to use an [HTTP proxy](https://www.jetbrains.com/help/idea/settings-http-proxy.html)
Somebody has asked about this before in the past and I also fixed the issue [here](https://github.com/Unthrottled/AMII/pull/93)
I installed Squid on my Ubuntu box and ran with this configurations, and it appears to still work!
> Added HTTP proxy support

- buildSrc/assets/templates/dark.dim.scheme.template.xml
- buildSrc/assets/templates/dark.dim.v2.scheme.template.xml
- buildSrc/assets/templates/dark.legacy.scheme.template.xml
- buildSrc/assets/templates/dark.scheme.template.xml
- buildSrc/assets/templates/light.dim.scheme.template.xml
- buildSrc/assets/templates/light.scheme.template.xml
- buildSrc/assets/templates/light.v2.scheme.template.xml
- buildSrc/assets/templates/vivid.v1.scheme.template.xml
- buildSrc/assets/themes/dragonMaid/kanna/dark/Kanna_Dark.xml
- buildSrc/assets/themes/eva/misato/dark/Misato_Dark.xml
- buildSrc/assets/themes/literature/natsuki/light/natsuki.light.jetbrains.definition.json
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/promotions/AniMemePluginPromotionRunner.kt
- src/main/kotlin/io/unthrottled/doki/promotions/PromotionManager.kt
- src/main/resources/theme-schema/master.theme.schema.json
- Removed `searchResultBackground` and replaced with `foldedTextBackground`
- Added a new color `identifierHighlight` which contrasts with the editor background.
- And a bunch of other small things.
I did this for all **44** themes
:sweat_smile: 
Closes #370 
| Before | After |
| --- | --- |
| ![Screenshot from 2021-04-09 18-52-35](https://user-images.githubusercontent.com/15972415/114252121-59138780-9969-11eb-98c0-7d6c4b9de181.png) | ![Screenshot from 2021-04-09 19-02-25](https://user-images.githubusercontent.com/15972415/114252124-5f096880-9969-11eb-8528-7c7cf28c3173.png) |
> Better Identifier Under Caret & Search Result Backgrounds

- buildSrc/assets/templates/base.laf.template.json
- changelog/CHANGELOG.md
- gradle.properties
- Using the deprecated `CompletionPopup.background` look and feel property to attempt to color the lookup window.
Some users have custom editor schemes that will not get the `LOOKUP_COLOR` on update, because they are old snapshots of color scheme past. Relates to #400 
> 2021.2 Lookup window for users with custom color schemes

- changelog/CHANGELOG.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/actions/ShowUpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/themes/ThemeManager.kt
- src/main/kotlin/io/unthrottled/doki/themes/impl/ThemeManagerImpl.kt
- Changed the update notification from the regular popup window, to an HTML browser view of the new https://doki-theme.unthrottled.io
- All the cool kids are doing it, so why shouldn't I?
> Doki Theme Home

- buildSrc/assets/templates/base.laf.template.json
- buildSrc/assets/themes/literature/natsuki/light/natsuki.light.jetbrains.definition.json
- buildSrc/assets/themes/reZero/beatrice/beatrice.jetbrains.definition.json
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/icon/ColorPatcher.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/resources/icons/actions/lightning.svg
- src/main/resources/icons/actions/lightning_dark.svg
- Updates the colors used by the [IDE Features Trainer](https://plugins.jetbrains.com/plugin/8554-ide-features-trainer) plugin, for a more consistent learning experience.
- Small updates to some other things as well.
- Updated Natsuki Light & Beatrice's completion popup selection background, such that you can actually read the info foreground text.
- Themed the lightning bolt icon. 
Was learning cool IDE features, and was sad because it wasn't consistent.
> IDE Traning Theming & Other Stuff

- README.md
- build.gradle.kts
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- settings.gradle
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/themes/DokiTheme.kt
- Updated the update notification's fallback page to look less like garbage. 😭 
Closes #468 
> Enhanced Update UX

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/promotions/PromotionManager.kt
- src/main/kotlin/io/unthrottled/doki/service/UpdateNotificationUpdater.kt
- src/main/kotlin/io/unthrottled/doki/settings/actors/LafAnimationActor.kt
- src/main/kotlin/io/unthrottled/doki/settings/actors/ShowReadmeActor.kt
- src/main/kotlin/io/unthrottled/doki/settings/actors/ThemedTitleBarActor.kt
- src/main/kotlin/io/unthrottled/doki/util/Debouncer.kt
- Turning off the Doki Theme Home's wallpaper if the user has set the wallpaper setting in the IDE.
- Update Notification updates on LaF Change. 
Closes #499 
> Update Notification Double Wallpaper Fix

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/java/io/unthrottled/doki/settings/ThemeSettingsUI.java
- src/main/kotlin/io/unthrottled/doki/hax/HackComponent.kt
- src/main/kotlin/io/unthrottled/doki/settings/ThemeSettings.kt
- Using JetBrains Font combo box instead of loading all font information and putting it in a combo box.
Probably closes #507 
> Deferring Font Loading to JetBrains font combo-box.

- changelog/CHANGELOG.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/stickers/StickerPane.kt
- Fixed issue where the previous theme's sticker would _stick around_ behind the current theme's sticker. <sup><sup>I'll see myself out</sup></sup>
Fixes bug introduced in #514 
Fixes this: 👇 
> Fixed Sticker Residue on LaF Switch

- README.md
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/legacy/EXPUIBastardizer.kt
- src/main/kotlin/io/unthrottled/doki/stickers/StickerComponent.kt
- src/main/kotlin/io/unthrottled/doki/stickers/StickerPaneService.kt
- Vertically aligned the editor search text input on the new UI.
- Allow custom stickers to remain on IDE for non-Doki themes.
closes #633 
| Before | After |
| --- | --- |
| <img width="1299" alt="Screenshot 2023-02-01 at 7 55 18 PM" src="https://user-images.githubusercontent.com/15972415/216216224-777ff62e-d890-4d03-97c9-cffc0cf4141b.png"> | <img width="1216" alt="Screenshot 2023-02-01 at 7 55 04 PM" src="https://user-images.githubusercontent.com/15972415/216216264-ac19f770-0935-4fda-afcd-dd1041f4ba48.png"> |
> New UI Search Field Padding Fix

- buildSrc/assets/templates/base.laf.template.json
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/BuildThemes.kt
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/legacy/EXPUIBastardizer.kt
- Themed EXP UI header button hover color
- Updated EXP UI project tree spacing to mirror JetBrains' defaults.
Consistency is cool 😎 
> New UI Updates

- buildSrc/assets/templates/base.laf.template.json
- buildSrc/assets/templates/light.laf.template.json
- buildSrc/assets/themes/nekoPara/shigure/light/shigure.light.jetbrains.definition.json
- buildSrc/src/main/kotlin/BuildThemes.kt
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- Made Light Theme's checkboxes & radio buttons more usable.
- Sigure's list item selection is readable now.
- Updated Sagiri's syntax highlight to avoid looking like an error.
closes #649 
closes #647 
> Usability Stuff

- build.gradle.kts
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/stickers/StickerPane.kt
- src/main/kotlin/io/unthrottled/doki/util/LAFAnimator.kt
- src/main/kotlin/io/unthrottled/doki/util/ToolBox.kt
- Updated Kotlin to 2.0.0 because that's what the platform is going to have
- Updated some of the APIs to match the 2024.3 SDK
- Removed the janky markdown to HTML plugin (probably putting it back later with the changelog plugin?)
>Starting with version 2024.3, there will be a dedicated JSON plugin, replacing the JSON module that was previously part of the platform. Therefore, please declare an explicit dependency on com.intellij.modules.json to ensure compatibility with version 2024.3. In the meantime, we have limited the until-build to 242.* for the plugin [Doki Theme](https://plugins.jetbrains.com/plugin/10804-doki-theme/edit).
☝️ Message from the plugin peoples, so going to have to re-instate that, but the 2024.3 build doesn't work on my machine, something about the instance not being …
> 2024.3 Build Support

- CONTRIBUTING.md
Fix a typo at github username environment variable: GITHUB_TOKEN was replaced with GITHUB_ACTOR.
> :adhesive_bandage: typo at GITHUB user environment variable
