- docs/CHANGELOG.md
- src/main/java/com/chrisrm/idea/actions/ClubMemberManager.java
#8 
Works on 
WebStorm 2018.1.3
Build #WS-181.4892.44, built on May 8, 2018
Subscription is active until February 20, 2019
JRE: 1.8.0_152-release-1136-b38 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-43-generic
PyCharm 2018.1.2 (Professional Edition)
Build #PY-181.4668.75, built on April 25, 2018
Subscription is active until February 20, 2019
JRE: 1.8.0_152-release-1136-b29 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-43-generic
CLion 2018.1.2
Build #CL-181.4668.70, built on April 24, 2018
Subscription is active until February 20, 2019
JRE: 1.8.0_152-release-1136-b29 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-43-generic
- [ X ] Bug fix …
> less depending on library to copy stuffs

- docs/CHANGELOG.html
- docs/CHANGELOG.md
- gradle.properties
- src/main/java/com/chrisrm/idea/utils/MTUiUtils.java
- src/main/resources/colors/Material Monika.xml
- src/main/resources/colors/Material Natsuki.xml
- src/main/resources/colors/Material Sayori.xml
- src/main/resources/colors/Material Yuri.xml
Makes doing PR's not want to tear my eye's out.
> Diff colors

- src/main/java/com/chrisrm/idea/themes/literature/club/DokiDokiTheme.java
- src/main/java/com/chrisrm/idea/themes/literature/club/MonikaTheme.kt
> More better inactive text color

- src/main/resources/com/chrisrm/idea/natsuki_windows.properties
> Light Natsuki Selection conformity.

- src/main/resources/colors/Monika.xml
> More able to read light monika diff conflicts

- build.gradle
- gradle.properties
- src/main/java/io/acari/DDLC/DDLCHackComponent.kt
> Monika's writing tip of the day (Revisited)

- docs/CHANGELOG.html
- docs/CHANGELOG.md
- gradle.properties
- src/main/java/com/chrisrm/ideaddlc/lafs/MTLafInstaller.java
- src/main/java/com/chrisrm/ideaddlc/utils/MTUiUtils.java
- src/main/resources/messages/MaterialThemeBundle.properties
- Android Studio 3.3.2 Support
#144
> Android 3.3.2 support

- build.gradle
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- src/main/kotlin/io/acari/doki/notification/UpdateNotification.kt
- src/main/resources/META-INF/plugin.xml
- themes/definitions/mistress/wyla/Wyla.xml
- themes/templates/dark.scheme.template.xml
- themes/templates/light.scheme.template.xml
Updated default font to `Victor Mono` and fall back to `JetBrains Mono` if not available.
Also updated spacing to `1.1`. Slightly adjusted the console green to support the new font for light themes.
Me likey the cursive code font and I want it on all my IDEs.
> Fonts n Stuff

- README.md
- build.gradle
- buildSrc/src/main/kotlin/BuildThemes.kt
- buildSrc/src/main/kotlin/Models.kt
- buildSrc/src/main/kotlin/Tools.kt
- src/main/kotlin/io/acari/doki/TheDokiTheme.kt
- src/main/kotlin/io/acari/doki/config/ThemeConfig.kt
- src/main/kotlin/io/acari/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/acari/doki/settings/ThemeSettings.kt
- src/main/kotlin/io/acari/doki/settings/actors/ThemeActor.kt
- src/main/kotlin/io/acari/doki/stickers/StickerService.kt
- src/main/kotlin/io/acari/doki/stickers/impl/StickerServiceImpl.kt
- src/main/kotlin/io/acari/doki/themes/ThemeManager.kt
- src/main/kotlin/io/acari/doki/util/ThemeMigrator.kt
- src/main/resources/META-INF/plugin.xml
- themes/templates/base.laf.template.json
- themes/templates/dark.laf.template.json
- themes/templates/dark.scheme.template.xml
- themes/templates/light.laf.template.json
- themes/templates/light.scheme.template.xml
- todo
- Adjusted console colors to be more readable for light themes.
- Moved theme suite: Mistress's Menagerie, from Community Themes to Ultimate Themes.
I am fine with being weird, but I still am a little hesitant to share this plugin because of these themes. 
I still want them, so I'll just put them in a separate product.
Works on my linux box. This is a pre-release, so not going to be published.
> Ultimate Themes

- README.md
- build.gradle
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- src/main/kotlin/io/acari/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/acari/doki/util/ThemeMigrator.kt
Dispatches legacy theme migration message later.
Makes sure that users that had a legacy theme are notified that the theme is no longer available.
> Better Legacy Theme Migration

- build.gradle
- buildSrc/src/main/kotlin/BuildThemes.kt
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- src/main/kotlin/io/acari/doki/notification/UpdateNotification.kt
Cleaning the resources directory on build.
I bundled the ultimate themes with the community plugin, and they showed up in the settings combo box. Selecting an ultimate theme causes an exception to get thrown, which was reported to me.
Works on 
```
IntelliJ IDEA 2019.3.4 (Ultimate Edition)
Build #IU-193.6911.18, built on March 17, 2020
You have a perpetual fallback license for this version
Runtime version: 11.0.6+8-b520.43 amd64
Linux 4.15.0-91-generic
Memory: 512M
Cores: 12
Registry: java.completion.argument.hints.internal=false
```
> Fixed Settings Bug

- build.gradle
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- src/main/kotlin/io/acari/doki/hax/HackComponent.kt
- src/main/kotlin/io/acari/doki/laf/LookAndFeelInstaller.kt
- src/main/kotlin/io/acari/doki/notification/UpdateNotification.kt
- src/main/resources/icons/debugger/watch.svg
- themes/definitions/danganronpa/ibuki/dark/Ibuki_Dark.xml
- themes/definitions/danganronpa/ibuki/dark/ibuki.dark.jetbrains.definition.json
- themes/definitions/killLaKill/satsuki/Satsuki.xml
- themes/templates/base.laf.template.json
- themes/templates/dark.scheme.template.xml
- themes/templates/light.scheme.template.xml
Changed a whole bunch of small things.
Small Issues thread #199 
Some things
> Small fixes

- build.gradle
- buildSrc/src/main/kotlin/BuildThemes.kt
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- themes/definitions/literature/monika/light/Monika_Light.xml
- themes/definitions/literature/monika/light/monika.light.jetbrains.definition.json
- themes/definitions/literature/sayori/light/Sayori_Light.xml
- themes/definitions/literature/sayori/light/sayori.light.jetbrains.definition.json
- themes/definitions/literature/yuri/light/Yuri_Light.xml
- themes/definitions/literature/yuri/light/yuri.light.jetbrains.definition.json
- Revisited most of the light themes so they are all consistent with the other products.
- Themes affected:
- Light Monika
- Light Natsuki
- Light Yuri
- Light Sayori
- Beatrice
Well I really like how Light Emilia looks, so I made the other light themes have the same tone as well.
Works on this
```
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 29, 2020
Runtime version: 11.0.6+8-b765.40 amd64
Linux 4.15.0-99-generic
Memory: 3972M
Cores: 12
Registry: ide.intellij.laf.enable.animation=true, ide.open.readme.md.on.startup=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, Key Promoter X, …
```
> Legacy enhancement

- build.gradle
- changelog/CHANGELOG.html
- changelog/CHANGELOG.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
Provide support for the 2020.2 Builds
The 2020.2 EAP is here! :confetti_ball: 
Works on my machine :smile: 
> Add 2020.2 build support and bump version to 7.2.1

- .github/workflows/release.yml
- ciScripts/buildPlugin.sh
Adds GitHub Workflow to publish assets to release.
Fixes #238 
:shrug: I haven't yet
> Added release pipeline

- build.gradle
- changelog/CHANGELOG.md
- themes/definitions/eva/misato/dark/misato.dark.jetbrains.definition.json
- Updated Misato's green syntax highlight color.
I like the green, I just wanted a less lime (yellow/green) color.
Works on:
```
Linux 4.15.0-109-generic
Memory: 512M
Cores: 12
```
> Small enhancements

- build.gradle
- changelog/CHANGELOG.md
- Updated Misato's selection inactive color
I could not read the accented font in the selected row.
Works on this:
```
Linux 4.15.0-109-generic
Memory: 512M
Cores: 12
```
> Updated changelog and bumped version to v9.0.2

- build.gradle
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- src/main/kotlin/io/unthrottled/doki/integrations/ErrorReporter.kt
- src/main/kotlin/io/unthrottled/doki/integrations/RestClient.kt
- src/main/kotlin/io/unthrottled/doki/stickers/impl/StickerServiceImpl.kt
- src/main/kotlin/io/unthrottled/doki/themes/impl/ThemeManagerImpl.kt
- Actually handling runtime exceptions when attempting to perform remote operations.
- Hopefully address some of the [network error](https://sentry.io/share/issue/0e10eaee924346b2bbb374f6efcc995c/) issues that pop up occasionally. :crossed_fingers: 
Works on 
```
Linux 4.15.0-111-generic
Memory: 512M
Cores: 12
```
> Asset Resiliency 

- .github/workflows/preMerge.yml
- Added platform compatibility checks to pre-merge
I've had this put in other project, I just figured I'd bring it here.
I haven't, yolo.
> Added Platform Compatibility checks

- build.gradle
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- src/main/kotlin/io/unthrottled/doki/assets/AssetManager.kt
- src/main/kotlin/io/unthrottled/doki/promotions/MotivatorPromotionDialog.kt
- src/main/kotlin/io/unthrottled/doki/promotions/PromotionManager.kt
- src/test/kotlin/io/unthrottled/doki/promotions/PromotionManagerIntegrationTest.kt
Added GitHub as a secondary asset source when unable to get assets from https://doki.assets.unthrottled.io . 
Closes #266 
I figured that Microsoft has their stuff together, and wont have international host resolution issues. So just fall back and use that if need be :)
I ran through all of the themes with the fall back as primary and it all worked :D
> Asset Source Fallback

- build.gradle
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- src/main/kotlin/io/unthrottled/doki/hax/HackComponent.kt
- themes/definitions/reZero/emilia/dark/Emilia_Dark.xml
- themes/templates/base.laf.template.json
- Changed Emilia Dark's syntax coloring
- Comments
- A bunch of small fixes. [Please see issue for more details](https://github.com/doki-theme/doki-theme-jetbrains/issues/269)
Closes #269 
Works on
```
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64
Linux 4.15.0-117-generic
Memory: 512M
Cores: 12
Non-Bundled Plugins: Key Promoter X, org.jetbrains.jumpToLine, io.acari.DDLCTheme, zd.zero.waifu-motivator-plugin
```
> Consistency Fixes

- build.gradle
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- src/main/kotlin/io/unthrottled/doki/icon/IconLookup.kt
- src/main/kotlin/io/unthrottled/doki/integrations/ErrorReporter.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- themes/templates/base.laf.template.json
- Bumped Kotlin Build
- Bumped Gradle Wrapper Version
- Stylized the new welcome screen.
- Fixed issue with check-boxes on the 2020.3 builds.
Closes #275 
Works on these envs:
```
IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
Build #IU-203.3645.34, built on September 21, 2020
Expiration date: October 21, 2020
Runtime version: 11.0.8+10-b1094.1 amd64
Linux 4.15.0-117-generic
Memory: 512M
Cores: 12
Non-Bundled Plugins: org.jetbrains.jumpToLine, io.acari.DDLCTheme
```
```
PhpStorm 2020.2.1
Build #PS-202.6948.87, built on August 27, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: …
```
> 2020.3 Support

- build.gradle
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- src/main/kotlin/io/unthrottled/doki/hax/HackComponent.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/ui/TitlePaneUI.kt
- themes/templates/base.laf.template.json
Not drawing the title bar header on the Mac Sheet Message anymore.
Closes #283 
It works on MacOS :smiley: 
> MacOS Title Pane Fix

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/assets/LocalAssetService.kt
Being more careful when persisting the asset check dates.
Fixes [this reported issue](https://sentry.io/share/issue/29ebf6209d0048c5a22b8513770b925f/)
Works on
```
IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
Build #IU-203.4818.26, built on October 14, 2020
Expiration date: November 13, 2020
Runtime version: 11.0.8+10-b1129.2 amd64
Linux 5.4.0-52-generic
Memory: 512M
Cores: 12
```
> Asset check safety [Bug Fix]

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/actions/MotivatorPromotion.kt
- src/main/kotlin/io/unthrottled/doki/promotions/MotivatorPluginPromotionRunner.kt
- src/main/kotlin/io/unthrottled/doki/promotions/PromotionManager.kt
- src/test/kotlin/io/unthrottled/doki/promotions/PromotionManagerIntegrationTest.kt
- Fixed issue when running promotion and all projects are closed
Fixes #296
I wrote some tests around the issue, so it should be fine :sweat: 
> Motivator Promotion Bug Fix

- build.gradle.kts
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/assets/AssetManager.kt
- src/main/kotlin/io/unthrottled/doki/integrations/ErrorReporter.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- Updated plugin dependencies including the Sentry client
Figured I'd sneak this in before releasing to marketplace.
Plus I was getting class path errors when including this plugin as a dependency of amii.
It works on this:
```
IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
Subscription is active until February 20, 2021.
Runtime version: 11.0.9.1+11-b1145.63 amd64
Windows 10 10.0
Memory: 512M
Cores: 12
Non-Bundled Plugins: io.acari.DDLCTheme, org.jetbrains.jumpToLine
```
> Dependencies Upgrades

- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
Only added a "know" in the UpdateNotification.kt file. I'm sorry if this isn't a important change, but I wanted to fix that 🤷
I did it because it drove me nuts.
> literally added an "know" in the UpdateNotification.kt.

- .github/dependabot.yml
- build.gradle.kts
- changelog/CHANGELOG.md
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- Added dependabot and updated dependencies
- Updated changelog and bumped version to v12.2.1
- Update plugin's build dependencies
Closes #294
Well, it works on:
```
IntelliJ IDEA 2020.3.2 Preview (Ultimate Edition)
Build #IU-203.7148.15, built on January 13, 2021
Subscription is active until February 20, 2021.
Runtime version: 11.0.9.1+11-b1145.75 amd64
Linux 5.4.0-62-generic
Memory: 512M
Cores: 12
```
> Build Dependency Upgrade

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/stickers/StickerPane.kt
- src/main/kotlin/io/unthrottled/doki/stickers/StickerPaneService.kt
- themes/definitions/literature/yuri/dark/yuri.dark.jetbrains.definition.json
- themes/definitions/reZero/emilia/dark/emilia.dark.jetbrains.definition.json
- themes/templates/base.laf.template.json
- Fixed bug where stickers disappear when attempting to close a window.
- Many small changes to every theme's look and feel [see issue for more details](https://github.com/doki-theme/doki-theme-jetbrains/issues/306)
Closes #306
I tested all 36 themes....I have a bunch of themes.....
> Consistency Updates

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/themes/DokiTheme.kt
- src/main/resources/META-INF/plugin.xml
- Added 2021.1 build support
- Bumped lowest support IDE to avoid compatability problems when reporting errors
Closes #318
Works on 2021.1 EAP and 2020.3.2.
> 2021.1 build support

- changelog/CHANGELOG.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/assets/LocalAssetService.kt
- src/main/kotlin/io/unthrottled/doki/legacy/LegacyMigration.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/stickers/BackgroundWallpaperService.kt
- Removed a bunch of legacy migration code.
I am going to release this version to the marketplace, so it is time to clean up the code.
Works on 
```
IntelliJ IDEA 2021.1 EAP (Ultimate Edition)
Build #IU-211.4961.33, built on January 27, 2021
Expiration date: February 26, 2021
Runtime version: 11.0.9.1+11-b1257.1 amd64
Linux 5.4.0-65-generic
Memory: 512M
Cores: 12
Non-Bundled Plugins: io.acari.DDLCTheme (12.5.2)
Kotlin: 211-1.4.21-release-IJ4961.6
```
> Migration cleanup

- changelog/CHANGELOG.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/hax/HackComponent.kt
- themes/definitions/killLaKill/ryuko/Ryuko.xml
- themes/definitions/konoSuba/Megumin.xml
- themes/templates/dark.scheme.template.xml
- themes/templates/light.scheme.template.xml
- Added INLAY_DEFAULT for default inline parameter hints
- Updated the run anything separator color
Closes #333
Works on 
```
IntelliJ IDEA 2021.1 EAP (Ultimate Edition)
Build #IU-211.5787.15, built on February 10, 2021
Expiration date: March 12, 2021
Runtime version: 11.0.2+7-LTS amd64
VM: OpenJDK 64-Bit Server VM by Azul Systems, Inc.
Linux 5.4.0-65-generic
Memory: 512M
Cores: 12
Non-Bundled Plugins: io.acari.DDLCTheme (13.0.1)
Kotlin: 211-1.4.21-release-IJ5787.2
```
> 2021.1 Build Consistency

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/java/io/unthrottled/doki/settings/ThemeSettingsUI.form
- src/main/java/io/unthrottled/doki/settings/ThemeSettingsUI.java
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/actions/ShowSettingsAction.kt
- src/main/kotlin/io/unthrottled/doki/actions/SwapStickerAction.kt
- src/main/kotlin/io/unthrottled/doki/config/ThemeConfig.kt
- src/main/kotlin/io/unthrottled/doki/settings/ThemeSettings.kt
- src/main/kotlin/io/unthrottled/doki/settings/actors/BackgroundActor.kt
- src/main/kotlin/io/unthrottled/doki/settings/actors/EmptyFrameBackgroundActor.kt
- src/main/kotlin/io/unthrottled/doki/settings/actors/StickerActor.kt
- src/main/kotlin/io/unthrottled/doki/stickers/EditorBackgroundWallpaperService.kt
- src/main/kotlin/io/unthrottled/doki/stickers/EmptyFrameWallpaperService.kt
- src/main/kotlin/io/unthrottled/doki/stickers/StickerComponent.kt
- src/main/kotlin/io/unthrottled/doki/ui/status/ThemeStatusBarWidget.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/messages/MessageBundle.properties
- You can now enable/disable content provided by this plugin:
- The Sticker in the corner
- The empty editor background image
- The editor wallpaper
- Re-Vamped the settings UI
Closes #338 
> Granular Content Management

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- Bumped max supported build version to 2021.2
- New EAP came out today!! :tada:
> Added 2021.2 Build Support

- build.gradle.kts
- changelog/CHANGELOG.md
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/legacy/LegacyMigration.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/promotions/MemePromotionDialog.kt
- src/main/kotlin/io/unthrottled/doki/promotions/PromotionManager.kt
- src/main/kotlin/io/unthrottled/doki/service/PluginService.kt
- src/main/kotlin/io/unthrottled/doki/settings/actors/ThemeActor.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/io/unthrottled/doki/promotions/PromotionManagerIntegrationTest.kt
- Updated the plugin's [intellij gradle](https://lp.jetbrains.com/gradle-intellij-plugin/) plugin to 1.0
- Fixed 2021.2 build issues
- The 2021.1 RC was cached on my local machine, that's why build's worked for me an not the CI
> Build Updates

- build.gradle.kts
- buildSrc/assets/templates/dark.scheme.template.xml
- buildSrc/assets/templates/light.scheme.template.xml
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/resources/META-INF/io.unthrottled.doki.theme-com.intellij.modules.lang.xml
- src/main/resources/META-INF/plugin.xml
- Plugin is now supported on the `Code With Me` platform.
Closes #427 
> Code With Me Support

- buildSrc/assets/templates/dark.scheme.template.xml
- buildSrc/assets/templates/light.scheme.template.xml
- changelog/CHANGELOG.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- Updated the version control uncommitted line markers on the right-hand side (next the scrollbar) to be more visible.
- Closes #446 
| Before | After |
| --- | --- |
| ![Screenshot from 2021-09-06 06-03-31](https://user-images.githubusercontent.com/15972415/132208364-cbb24177-6077-401a-838c-72ec74158106.png) | ![Screenshot from 2021-09-06 06-01-42](https://user-images.githubusercontent.com/15972415/132208386-cf12c9e0-613a-48ad-82c7-f6eb2bfa4b37.png) |
> More Distingushable VCS markers

- buildSrc/assets/templates/base.laf.template.json
- buildSrc/assets/templates/dark.scheme.template.xml
- buildSrc/assets/templates/light.scheme.template.xml
- buildSrc/assets/themes/nekoPara/chocola/xmas/chocola.xmas.jetbrains.definition.json
- changelog/CHANGELOG.md
- gradle.properties
- src/main/resources/META-INF/plugin.xml
- Actually theming the Mnemonic bookmark icons this time.
Last PR for a while (I hope)
> Mnemonic Bookmark Theming

- src/main/resources/messages/MessageBundle_ru.properties
Translated: `Randomly pick theme`
> Update the translation

- src/main/resources/messages/MessageBundle_ru.properties
Translated:
`Hide on hover`
`Hide delay (ms)`
> Translate new added fields

- build.gradle.kts
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/java/io/unthrottled/doki/settings/ThemeSettingsUI.form
- src/main/java/io/unthrottled/doki/settings/ThemeSettingsUI.java
- src/main/kotlin/io/unthrottled/doki/promotions/CulturedContentDialog.kt
- src/main/kotlin/io/unthrottled/doki/settings/ThemeSettings.kt
- src/main/kotlin/io/unthrottled/doki/ui/DokiRadioButtonUI.kt
- Added the initial support for the 2022.3 platform.
- Theys keeps updating their platform....
> Added Initial 2022.3 Build Support.

- build.gradle.kts
- buildSrc/assets/templates/dark.scheme.template.xml
- buildSrc/assets/templates/light.scheme.template.xml
- changelog/CHANGELOG.md
- gradle.properties
- src/main/resources/META-INF/plugin.xml
- Themed the new `Diff & Merge` `Folded unchanged fragments` `Wave` separator.  
https://github.com/JetBrains/intellij-community/commit/e8c2875868762e0364348f75292a6426edc92db1
| Before | After |
| --- | --- |
| <img width="1221" alt="Screen Shot 2022-09-28 at 5 21 03 PM" src="https://user-images.githubusercontent.com/15972415/192902704-e79faf80-4b06-4b28-a18b-2396eb9f74bf.png"> | <img width="1221" alt="Screen Shot 2022-09-28 at 5 43 19 PM" src="https://user-images.githubusercontent.com/15972415/192902715-129512b2-6dee-4cd4-8b28-5255c9dde31a.png"> |
> Themed the new folded wave separator.

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/java/icons/DokiThemeIcons.java
- src/main/resources/META-INF/plugin.xml
- Moved all icon loading to the icon loading APIs.
Probably closes #580 
> Potentially Fixing Icon Loading Issue.

- buildSrc/assets/templates/base.laf.template.json
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- Themed the segmented buttons, so various settings UI components look better.
- 
Looked like this before 
> Themed Segmented Buttons

- buildSrc/assets/templates/base.laf.template.json
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- Added better EXP UI support (lookup window and some other stuffs)
- Themed the progress indicator track bar.
Don't like the Darcula colors bleeding into my themes. 
> Better EXP UI Support

- .github/ISSUE_TEMPLATE/bug_report.md
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/promotions/LedgerMaster.kt
- src/main/kotlin/io/unthrottled/doki/stickers/StickerComponent.kt
- src/main/kotlin/io/unthrottled/doki/themes/impl/ThemeManagerImpl.kt
- Added the initial 2023.1 build support. 
They keep releasing new versions of their platform....
> v88.3-1.8.2 - Initial 2023.1 Build Support

- CONTRIBUTING.md
- buildSrc/assets/templates/dark.scheme.template.xml
- buildSrc/assets/templates/light.scheme.template.xml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/BuildThemes.kt
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- Updated the border color of the `Code Lens` feature.
- Updated contributing documentation for new build process requirements.
closes #614 
> Enhancments n stuff

- buildSrc/assets/templates/dark.scheme.template.xml
- buildSrc/assets/templates/light.scheme.template.xml
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/java/io/unthrottled/doki/settings/ThemeSettingsUI.form
- src/main/java/io/unthrottled/doki/settings/ThemeSettingsUI.java
- Themed New UI Scrollbars in Rider to be consistent.
- Fixed the settings window in builds `231.6890.12`+ 
Closes #637 
> Settings Menu Fix

- buildSrc/assets/templates/dark.scheme.template.xml
- buildSrc/assets/templates/light.scheme.template.xml
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/TheDokiTheme.kt
- src/main/kotlin/io/unthrottled/doki/integrations/ErrorReporter.kt
- src/main/kotlin/io/unthrottled/doki/legacy/EXPUIFixer.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/ui/status/ThemeStatusBarWidget.kt
- src/main/resources/META-INF/plugin.xml
- Migrated to newer platform APIs
- Raised the lowest supported version to 2022.3
They are probably going to yell at me when I submit this plugin to the marketplace.
> Plugin Maintenance

- buildSrc/assets/templates/base.laf.template.json
- buildSrc/assets/templates/dark.scheme.template.xml
- buildSrc/assets/templates/light.scheme.template.xml
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/resources/icons/gutter/mnemonic.svg
- src/main/resources/icons/gutter/mnemonic_dark.svg
- src/main/resources/icons/nodes/mnemonic.svg
- src/main/resources/icons/nodes/mnemonic_dark.svg
- src/main/resources/mappings/ui-icons.path.mappings.json
- More usable Mnemonic Bookmarks
closes #659 
> Better Mnemonic Bookmarks

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/stickers/StickerPaneService.kt
- Added sticker placement to the welcome window.
closes #678 
> Added sticker placement to the welcome window.

- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- src/main/kotlin/io/unthrottled/doki/icon/DokiIcons.kt
- src/main/resources/mappings/ui-icons.path.mappings.json
- Added initial 2023.2 build support
They keep updating their platform
> Added initial 2023.2 build support.

- build.gradle.kts
- buildSrc/assets/templates/base.laf.template.json
- buildSrc/src/main/kotlin/BuildThemes.kt
- changelog/CHANGELOG.md
- changelog/RELEASE-NOTES.md
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- src/main/kotlin/io/unthrottled/doki/hax/SvgLoaderHacker.kt
- src/main/kotlin/io/unthrottled/doki/icon/ColorPatcher.kt
- src/main/kotlin/io/unthrottled/doki/integrations/ErrorReporter.kt
- src/main/kotlin/io/unthrottled/doki/integrations/XPathListener.kt
- src/main/kotlin/io/unthrottled/doki/listener/PluginPostStartUpActivity.kt
- src/main/kotlin/io/unthrottled/doki/notification/UpdateNotification.kt
- src/main/kotlin/io/unthrottled/doki/stickers/StickerComponent.kt
- src/main/kotlin/io/unthrottled/doki/stickers/StickerPaneService.kt
- src/main/kotlin/io/unthrottled/doki/themes/ThemeManager.kt
- src/main/kotlin/io/unthrottled/doki/themes/impl/ThemeManagerImpl.kt
- src/main/resources/META-INF/io.unthrottled.doki.theme-XPathView.xml
- src/main/resources/META-INF/plugin.xml
- Added 2023.3 build support
Closes #730 
Closes #742 
Closes #739 
Closes #733
> Added 2023.3 Build Support.
